Ref
Week-5/ecommerce pull request #65
Opened 2021-12-06 22:32 UTC by quiyetbrul

2021-12-06 23:40 UTC, quiyetbrul commented
handlebars in this branch arent updating... cant test front end properly...

2021-12-06 23:53 UTC, quiyetbrul commented
PLS DO NOT MERGE. I JUST SAW MORE UPDATES ON THE SERVER.JS

2021-12-07 17:08 UTC, dannyreina requested changes

2021-12-07 17:08 UTC, dannyreina commented on controllers/cart.js
> +  res.status(200).render('homepage', { data });
render cart page

2021-12-07 17:08 UTC, dannyreina commented on controllers/item.js
> +  res.status(200).redirect(`/users/${user.username}`);
apply 301 code

2021-12-07 17:08 UTC, dannyreina commented on controllers/user.js
> +	res.status(200).redirect(`/homepage/${newUser.username}`);
apply 301 code

2021-12-07 17:08 UTC, dannyreina commented on controllers/user.js
> +	res.status(200).redirect(`/users/${user.username}`);
apply 301 code

2021-12-08 20:41 UTC, merged